services:
  uptime-kuma:
    image: elestio/uptime-kuma:${SOFTWARE_VERSION_TAG}
    restart: unless-stopped

    volumes:
      - ./data:/app/data

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true