services:
  jellyfin:
    image: jellyfin/jellyfin:${SOFTWARE_VERSION_TAG}
    restart: unless-stopped

    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${MOVIES_FOLDER}:/media/movies
      - ${MUSIC_FOLDER}:/media/music
      - ${SHOWS_FOLDER}:/media/shows
      - ${BOOKS_FOLDER}:/media/books

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true