services:
  nginx:
    image: nginx:${SOFTWARE_VERSION_TAG}
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./snippets:/etc/nginx/snippets
      - ./certs:/etc/nginx/certs:ro

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true