- Infraestrutura:
    - Portainer:
        href: https://portainer.lab
        icon: portainer
        siteMonitor: https://portainer.lab
    
    - pgAdmin:
        href: https://pgadmin.lab
        icon: pgadmin
        siteMonitor: https://pgadmin.lab

    - Kuma:
        href: https://kuma.lab
        icon: uptime-kuma
        siteMonitor: https://kuma.lab

- Apps:
    - Swing Music:
        href: https://swingmusic.lab
        icon: navidrome
        siteMonitor: https://swingmusic.lab
    
    - Jellyfin:
        href: https://jellyfin.lab
        icon: jellyfin.png
        siteMonitor: https://jellyfin.lab
        ping: https://jellyfin.lab