services:
  portainer:
    image: portainer/portainer-ce:${SOFTWARE_VERSION_TAG}
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    networks:
      - homelab-net

volumes:
  portainer_data:

networks:
  homelab-net:
    external: true