server {

    listen 443 ssl http2;

    server_name grafana.lab;

    include /etc/nginx/snippets/ssl.conf;

    location / {
        proxy_pass http://grafana:3000;

        include /etc/nginx/snippets/proxy-common.conf;
    }
}