server {

    listen 443 ssl http2;

    server_name pgadmin.lab;

    include /etc/nginx/snippets/ssl.conf;

    location / {
        proxy_pass http://pgadmin:80;

        include /etc/nginx/snippets/proxy-common.conf;
    }
}