server {

    listen 443 ssl http2;

    server_name swingmusic.lab;

    include /etc/nginx/snippets/ssl.conf;

    location / {
        proxy_pass http://swingmusic:1970;

        include /etc/nginx/snippets/proxy-common.conf;
    }
}