services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - homelab-net

volumes:
  pgadmin_data:

networks:
  homelab-net:
    external: true