services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${SOFTWARE_VERSION_TAG}
    restart: unless-stopped

    volumes:
      - ./config:/app/config
      - ${BACKGROUND_IMAGE}:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true